### PR TITLE
Don't hardcode c++ version compiler flags, use target_compile_features

### PR DESCRIPTION
**Pull request by autoantwort**
Maybe one should then also remove `/std:c++latest`

And 
```Cmake
    if(CMAKE_COMPILER_IS_GNUCXX)
        # required for #include <experimental/filesystem>
        target_link_libraries(${tgt} "stdc++fs")
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL Clang)
        target_link_libraries(${tgt} "stdc++fs")
    endif()
```
is probably also absolute, at least it worked without it for me.

### CODE REVIEW

**Comment by gknowles** [comment]
Thanks for the report!

It's been a while so I rechecked and the additional stdc++fs library is still required for gcc 8 and clang 8. I've added a version check so it's only be added if needed.

I also updated gcc 11 and clang 12 to std=c++2b.

The the language version is a hardcoded compiler flag because new language options appear in the compilers before they show up in cmake -- especially since I want to work with old versions of cmake. At the time I was adding std=c++2a  the cxx_std_20 option didn't exist. It's not important for most projects, but I want dimcli tested against the latest language options of the compilers. I actually wish the msvc std:c++latest flag was available on gcc & clang.

An alternative to compile features might be to set CMAKE_CXX_STANDARD to 17 (or 23?)... actually that still wouldn't work for old clang versions, where I had to change the transition version from c++1z to c++2a after the fact:
        # The libstdc++6 library, as of 2021-06-15, no longer works with
        # Clang++-6 in c++2a mode, failing with a reference to the unknown
        # std::is_constant_evaluated().

**Comment by autoantwort** [comment]
> It's not important for most projects, but I want dimcli tested against the latest language options of the compilers.

Im fine with it, but currently you force everybody to use the newest available c++ standard. Imho it would be better if the project only says "I need at least c++17" but everybody can choose the c++ standard they like (e.g by `-DCMAKE_C_FLAGS="std=c++2b"` or `-DCMAKE_CXX_STANDARD=20`).

**Comment by autoantwort** [comment]
And the `target_compile_features(${tgt} PUBLIC cxx_std_17)` line is still a good idea. It also catches compilers that you currently have not considered.

**Comment by gknowles** [comment]
There's nothing stopping you from putting -DCMAKE_CXX_STANDARD=17 on the command line. Setting CMAKE_CXX_STANDARD (or cxx_std_17) overrides the CMAKE_CXX_FLAGS settings. (I just tried it with CMake 3.22 on Windows and that's how it seems to work). 

OTOH, if you specify cxx_std_17 in the make file it can't be overridden on the command line.

I was about to add cxx_std_17 as a fallback for unknown compilers, but now it seems like maybe you'd be against using it at all since it can't be overridden?

**Comment by autoantwort** [comment]
> There's nothing stopping you from putting -DCMAKE_CXX_STANDARD=17 on the command line. Setting CMAKE_CXX_STANDARD (or cxx_std_17) overrides the CMAKE_CXX_FLAGS settings. (I just tried it with CMake 3.22 on Windows and that's how it seems to work).

Ok nice. Didn't know that. 

> OTOH, if you specify cxx_std_17 in the make file it can't be overridden on the command line.

Ok that you for finding that out. I thought is was the other way around!

> I was about to add cxx_std_17 as a fallback for unknown compilers, but now it seems like maybe you'd be against using it at all since it can't be overridden?

Yes. I will close this PR. Thank you :)

**Pull request closed without merging**
